### ISSUE TITLE
Major Organization Issue

### ISSUE THREAD

**Issue by spacebear27** [kachnov/WW13#117] opened 2017-07-12 17:38 UTC
The main problem that exists with organization in WW13, is it is difficult to tell rank when people are talking (worsened by authentic faction rank names that most people don't know). 

A possible solution to this, could be a number system, which places a number next to a speaker indicating their rank (i.e |0| - for Soldat and |6| - for Comandir). Furthermore, the text size of the speaker increases or decreases based on their rank (smaller for lower ranks and larger for higher ranks). Thus, making visibility of important speakers greater and less so for "grunts". 

Implementing these changes or something similar, would greatly improve both factions organization.

**Comment by tylerh95** [comment] 2017-07-14 01:25
Duplicate of #51

**Closed by tylerh95** 2017-07-14 01:25 UTC
