### ISSUE TITLE
Flammenwerfer throws too much flammen

### ISSUE THREAD

**Issue by OPacity2** [kachnov/WW13#133] opened 2017-07-13 20:06 UTC
The flammenwerfer at 60 output covers almost the whole screen in flames. While flamethrowers are devastating, I don't think they're that bad.

**Comment by OPacity2** [comment] 2017-07-13 20:08
And, uh, sorry if this isn't set up right, I dunno how to do this github stuff.

**Comment by kachnov** [comment] 2017-07-13 20:45
yeah, this is good

**Comment by tylerh95** [comment] 2017-07-14 01:16
Duplicate of #42

**Closed** 2017-07-14 01:16 UTC
Labels: duplicate
